### PR TITLE
Trigger new version to publish latest changes for gatsby 5

### PR DESCRIPTION
**Pull request by atrzaska**
Trigger new version to publish latest changes for gatsby 5

### CODE REVIEW

**Comment by atrzaska** [comment]
@JimmyBeldone PTAL

**Comment by atrzaska** [comment]
🍺

**Comment by atrzaska** [comment]
🥺

**Comment by atrzaska** [comment]
please merge this

**Comment by arancha-Honeypot** [comment]
I'd be nice to merge this PR in order to get rid of this annoying warning:
Captura de pantalla 2023-05-26 a las 16 31 21

**Comment by JimmyBeldone** [comment]
Hi :) 
Did you install last version ? 1.1.31

It should already be fixed, I forgot to close this PR

**Comment by JimmyBeldone** [comment]
I wasn't around for few months sorry for the delay.

PRs need to be done on 'develop' to run the CI, with a semantic prefix (fix, feat, ..)

I will add a contribute.md soon

**Comment by JimmyBeldone** [comment]
Let me know if you still have this warning with the latest version, I just tested it and no warning for me

**Comment by arancha-Honeypot** [comment]
Hi Jimmy, thanks for the quick response! I've the 1.1.31 version installed and still getting the warning.

**Comment by JimmyBeldone** [comment]
It's weird, I just created a fresh gatsby project with gatsby-cli and my plugin, no warning when starting or building the app.

This is the what I see when I look at my plugin `package.json` inside `node_modules` 

```
"peerDependencies": {
    "gatsby": "^2.0.0 || ^3.0.0 || ^4.0.0 || ^5.0.0"
  },
```

Could you try to uninstall / re install please ?

**Comment by arancha-Honeypot** [comment]
Sorry for the inconvenience. After removing the package-lock.json and run `npm install && npm update`, it has been solved! Probably some cached files we're around. Thanks!

**Comment by JimmyBeldone** [comment]
No worries :) Glad to read it !

**Pull request closed without merging**
